# Generated by Django 4.2.1 on 2023-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlib', '0003_alter_library_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='cover/', verbose_name='изображение'),
        ),
    ]
