# Generated by Django 4.2.3 on 2023-07-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainlib', '0004_alter_library_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='tittle',
        ),
    ]
